name: kmifqe
channels:
  - pytorch
  - nvidia
dependencies:
  - pytorch==1.13.1
  - numpy
  - pip:
    - mujoco-py==2.1.2.14
    - gym==0.17.2
    - d4rl==1.1
    - wandb
    - matplotlib
    - joblibs
    - pandas